name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes (UTC)
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Log Current Time (UTC)
        run: date -u

      - name: Curl your Render app
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://label-studio-on-render-x49n.onrender.com/
